using System;
using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Promociones.Domain.Models
{
    public class Promocion
    {
        public Promocion(Guid id, IEnumerable<string> mediosDePago, IEnumerable<string> bancos, IEnumerable<string> categoriasProductos, int? maximaCantidadDeCuotas, decimal? valorInteresCuotas, decimal? porcentajeDeDescuento, DateTime? fechaInicio, DateTime? fechaFin)
        {
            Id = id;
            MediosDePago = mediosDePago;
            Bancos = bancos;
            CategoriasProductos = categoriasProductos;
            MaximaCantidadDeCuotas = maximaCantidadDeCuotas;
            ValorInteresCuotas = valorInteresCuotas;
            PorcentajeDeDescuento = porcentajeDeDescuento;
            FechaInicio = fechaInicio;
            FechaFin = fechaFin;
        }

        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
        public Guid Id { get; private set; }
        public IEnumerable<string> MediosDePago { get; private set; }
        public IEnumerable<string> Bancos { get; private set; }
        public IEnumerable<string> CategoriasProductos { get; private set; }
        public int? MaximaCantidadDeCuotas { get; private set; }
        public decimal? ValorInteresCuotas { get; private set; }
        public decimal? PorcentajeDeDescuento { get; private set; }
        public DateTime? FechaInicio { get; private set; }
        public DateTime? FechaFin { get; private set; }
        public bool Activo { get; private set; }
        public DateTime FechaCreacion { get; private set; }
        public DateTime? FechaModificacion { get; private set; }

        //public Guid Id { get; set; }
        //public IEnumerable<string> MediosDePago { get; set; }
        //public IEnumerable<string> Bancos { get; set; }
        //public IEnumerable<string> CategoriasProductos { get; set; }
        //public int? MaximaCantidadDeCuotas { get; set; }
        //public decimal? ValorInteresCuotas { get; set; }
        //public decimal? PorcentajeDeDescuento { get; set; }
        //public DateTime? FechaInicio { get; set; }
        //public DateTime? FechaFin { get; set; }
        //public bool Activo { get; set; }
        //public DateTime FechaCreacion { get; set; }
        //public DateTime? FechaModificacion { get; set; }
    }
}
